# Generated by Django 3.0.5 on 2021-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('incident_description', models.TextField(blank=True)),
                ('incident_date_time', models.DateTimeField(auto_now_add=True)),
                ('incident_location', models.CharField(max_length=350)),
                ('severity', models.CharField(max_length=200)),
                ('suspected_cause', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('sub_incident', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Form_Data',
            },
        ),
    ]
